basePath: /
definitions:
  dto.AddUserDto:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        minLength: 5
        type: string
    required:
    - email
    - name
    - password
    type: object
  utils.ApiResponse:
    properties:
      data:
        additionalProperties: true
        type: object
      message:
        type: string
      status:
        type: integer
      success:
        type: boolean
    type: object
  utils.ValidationError:
    properties:
      field:
        type: string
      namespace:
        type: string
      tag:
        type: string
      type:
        type: string
      value: {}
    type: object
info:
  contact: {}
  description: This is scissor server.
paths:
  /students/create:
    post:
      consumes:
      - application/json
      description: Create User Account.
      parameters:
      - description: Add User Dto
        in: body
        name: requestBody
        required: true
        schema:
          $ref: '#/definitions/dto.AddUserDto'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            allOf:
            - $ref: '#/definitions/utils.ApiResponse'
            - properties:
                data:
                  type: boolean
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.ApiResponse'
        "422":
          description: Unprocessable Entity
          schema:
            allOf:
            - $ref: '#/definitions/utils.ApiResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/utils.ValidationError'
                  type: array
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.ApiResponse'
      summary: Create User.
      tags:
      - Student
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
